name:                typed-encoding
version:             0.2.0.0
github:              "rpeszek/typed-encoding"
license:             BSD3
author:              "Robert Peszek"
maintainer:          "robpeszek@gmail.com"
copyright:           "2020 Robert Peszek"


extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Type safe string transformations
category:            Data, Text

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:  See README.md in the project github repository.       
#   .
#   Type level annotations that make programming Strings safer.
#   .
#   Contains a list of Example modules.


dependencies:
- base >= 4.7 && < 5
- bytestring
- text
- base64-bytestring
- symbols


library:
  source-dirs: src
  ghc-options:
    - -fwarn-unused-imports
    - -fwarn-incomplete-patterns
    - -fprint-explicit-kinds

tests:
  typed-encoding-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typed-encoding
    - hspec
    - QuickCheck
    - quickcheck-instances
    other-modules: 
    - Test.Bc.IsStringRSpec

  typed-encoding-doctest:
    main:                Spec.hs
    source-dirs:         doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typed-encoding
    - QuickCheck
    - quickcheck-instances
    - doctest
    - doctest-discover
    